version: '2'
services:
  web-client:
    image: node:6.5.0
    network_mode: host
    ports:
      - "3000:3000"
    volumes:
      - ./web-client:/usr/src/app
      - ./assets:/usr/src/app/assets
    command: "/bin/bash -c \"cd /usr/src/app && npm run build:dll && tail -f /dev/null\""
    depends_on:
      - web-api
  web-api:
    image: node:6.5.0
    network_mode: host
    environment:
      - PG_HOST=localhost
    ports:
      - "3001:3001"
    volumes:
      - ./web-api:/usr/src/app
      - ./assets:/usr/src/app/assets
    command: "/bin/bash -c \"cd /usr/src/app && npm install && npm install -g gulp gulp-cli && tail -f /dev/null\""
    depends_on:
      - postgres
  postgres:
    image: postgres
    network_mode: host
    volumes:
      - ./dbdata:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    network_mode: host
    ports:
      - "6379:6379"
  rabbitmq:
    image: rabbitmq:3-management
    network_mode: host
    env_file: development.env
    ports:
      - "5672:5672"
      - "15672:15672"
      - "25672:25672"
  nginx:
    image: nginx
    network_mode: host
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web-client
      - web-api
  ml-predictor:
    image: node:6.5.0
    network_mode: host
    environment:
      - PG_HOST=localhost
    volumes:
      - ./ml-predictor:/usr/src/app
    working_dir: /usr/src/app
    command: "/bin/bash -c \"cd /usr/src/app && npm install && npm run start\""
    depends_on:
      - rabbitmq
  survey-training-preprocessor:
    image: python:3.5
    network_mode: host
    volumes:
      - ./assets:/usr/src/app/assets
      - ./survey-training-preprocessor:/usr/src/app
    command: "/bin/bash -c \"cd /usr/src/app && pip install --upgrade pip && pip install -r requirements.txt && python -u preprocessor.py\""
    depends_on:
      - postgres
      - redis
      - rabbitmq
    environment:
      - PG_HOST=localhost
  college-training-preprocessor:
    image: python:2.7
    network_mode: host
    volumes:
      - ./assets:/usr/src/app/assets
      - ./college-training-preprocessor:/usr/src/app
    command: "/bin/bash -c \"cd /usr/src/app && pip install --upgrade pip && pip install -r requirements.txt && python -u college_preprocessor.py\""
    depends_on:
      - postgres
      - redis
      - rabbitmq
    environment:
      - PG_HOST=localhost
  predictor-preprocessor:
    image: python:3.5
    network_mode: host
    volumes:
      - ./assets:/usr/src/app/assets
      - ./predictor-preprocessor:/usr/src/app
    command: "/bin/bash -c \"cd /usr/src/app && pip install --upgrade pip && pip install -r requirements.txt && python -u predictor-preprocessor.py\""
    depends_on:
      - redis
      - rabbitmq
      - survey-training-preprocessor
      - ml-predictor
