version: '2'
services:
  web-client:
    image: node:6.5.0
    expose:
      - "3000"
    volumes:
      - ./web-client:/usr/src/app
      - ./assets:/usr/src/app/assets
    command: "/bin/bash -c \"cd /usr/src/app && npm start\""
    depends_on:
      - web-api
  web-api:
    image: node:6.5.0
    env_file: production.env
    expose:
      - "3001"
    volumes:
      - ./web-api:/usr/src/app
      - ./assets:/usr/src/app/assets
    command: "/bin/bash -c \"cd /usr/src/app && npm start\""
    depends_on:
      - postgres
      - redis
  ml-predictor:
    image: node:6.5.0
    env_file: production.env
    volumes:
      - ./ml-predictor:/usr/src/app
    working_dir: /usr/src/app
    command: "/bin/bash -c \"cd /usr/src/app && sleep 3 && npm start\""
    depends_on:
      - rabbitmq
  postgres:
    image: postgres
    volumes:
      - ./dbdata:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    expose:
      - "6379"
  survey-training-preprocessor:
    image: python:3.5
    environment:
      PYTHONUSERBASE: /usr/src/app/vendor
      PYTHONPATH: ./survey-training-preprocessor
    volumes:
      - ./assets:/usr/src/app/assets
      - ./survey-training-preprocessor:/usr/src/app
    command: "/bin/bash -c \"cd /usr/src/app && python -u preprocessor.py\""
    depends_on:
      - postgres
      - redis
      - rabbitmq
    env_file: production.env
  rabbitmq:
    image: rabbitmq:3-management
    env_file: production.env
    expose:
      - "5672"
      - "15672" # RabbitMQ GUI server
      - "25672"
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx-prod.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web-client
      - web-api
  college-training-preprocessor:
    image: python:2.7
    environment:
      PYTHONUSERBASE: /usr/src/app/vendor
      PYTHONPATH: ./survey-training-preprocessor
    volumes:
      - ./assets:/usr/src/app/assets
      - ./college-training-preprocessor:/usr/src/app
    command: "/bin/bash -c \"cd /usr/src/app && python -u college_preprocessor.py\""
    depends_on:
      - postgres
      - redis
      - rabbitmq
    env_file: production.env
  predictor-preprocessor:
    env_file: production.env
    image: python:3.5
    environment:
      PYTHONUSERBASE: /usr/src/app/vendor
      PYTHONPATH: ./survey-training-preprocessor
    volumes:
      - ./assets:/usr/src/app/assets
      - ./predictor-preprocessor:/usr/src/app
    command: "/bin/bash -c \"cd /usr/src/app && python -u predictor-preprocessor.py\""
    depends_on:
      - redis
      - rabbitmq
      - survey-training-preprocessor
      - ml-predictor
